version: '2'

services:
  frontend:
    image: nginx
    restart: always
    volumes:
     - "$PWD/conf.d:/etc/nginx/conf.d:ro"
     - "$PWD:/usr/share/nginx/html"
    networks:
     - nginx_outside

networks:
  nginx_outside:
    external: true
